### PR TITLE
Responsive graph merge

### PR DESCRIPTION
**Pull request by mj3cheun**
## About
New feature to dash-cytoscape which closes an issue

## Description of changes 
Add property to make graph responsive (that is make the graph position and size respond to changes in the viewport).

## Pre-Merge checklist
- [x] The project was correctly built with `npm run build:all`.
- [x] If there was any conflict, it was solved correctly
- [ ] All changes were documented in CHANGELOG.md.
- [ ] All tests on CircleCI have passed.
- [ ] All Percy visual changes have been approved.
- [ ] Two people have :dancer:'d the pull request. You can be one of these people if you are a Dash Cytoscape core contributor.

## Reference Issues
Closes issue #62
An update of a previous PR made #70 

## Other comments

### CODE REVIEW

**Comment by mj3cheun** [comment]
Really not sure whats going on with those tests

**Comment by xhlulu** [comment]
There has been some instabilities with the tests recently, and it's hard to reproduce since they are not deterministic (sometimes pass, sometimes fail), work locally but not on CircleCI, and there's not much hint on why they are failing.

We are planning to take a deeper look into them before the next release. In order to not slow down this PR, let's aim for the tests to pass locally before merging.

Could you take at [Contributing](https://github.com/plotly/dash-cytoscape/blob/master/CONTRIBUTING.md) for more information on how to setup and run the tests? If it's not clear, or if something doesn't work, please let us know so we can improve the instructions.

**Comment by mj3cheun** [comment]
Ok thanks for the information. When I run the test_callbacks, test_interactions, and test_usage tests locally they all pass

Investigating the Percy tests, but this PR should not affect any of the other demos unless the responsive property is true, which is only the case for the responsive demo. Will report back when I know more.

**Comment by xhlulu** [comment]
Thank you! I'll try rerunning the test a few times to see if they can pass. Whenever I have the bandwidth, I will fork and run your branch locally too.

**Comment by xhlulu** [comment]
This is showing up in the tests:
```
======================================================================
 
ERROR: test_interactions (tests.test_interactions.Tests)
 
----------------------------------------------------------------------
 
Traceback (most recent call last):
 
  File "/home/circleci/project/tests/test_interactions.py", line 152, in test_interactions
 
    offset_x, offset_y = perform_dragging(init_x, init_y, 0, 0, elem_tap)
 
  File "/home/circleci/project/tests/test_interactions.py", line 98, in perform_dragging
 
    new_pos = elem_json.get('renderedPosition')
 
AttributeError: 'NoneType' object has no attribute 'get'
 

 
----------------------------------------------------------------------
 
Ran 1 test in 14.847s
 

 
FAILED (errors=1)
 
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49080), raddr=('127.0.0.1', 40569)>
 
 
Exited with code exit status 1 
CircleCI received exit code 1 
```

Can you check that particular test to see if it passes?

**Comment by mj3cheun** [comment]
Ok so a few new things I have discovered so far. As for the tests passing and failing, the test you have pointed out has always been failing and I have missed the fail message when running the tests on my computer, which is my bad. How this happened is when I pasted the following into the terminal to run the tests:

```
python -m unittest tests.test_callbacks
python -m unittest tests.test_interactions
python -m unittest tests.test_usage
```

I missed that to get the results of all 3 tests I need to scroll through the output all the way to the top looking for failed tests. What I did instead was look at the last line after all the tests finished, which gave only the results for the last test. (`python -m unittest tests.test_usage`)

I have also figured out why the test is failing. Seems that the positions of the nodes in `usage-events.py` has shifted, meaning that the expected click positions are wrong, resulting in failing tests. Working to figure out why the node positions have shifted.

ezgif com-gif-maker (1)

**Comment by mj3cheun** [comment]
Upon further testing i have found that this graph shifting problem resulting in failing tests might be the result of something that is already in the master branch rather than this feature branch.

To reproduce:
checkout to master
build
run test (`python -m unittest tests.test_interactions`)

Do you mind confirming if this is in fact the case? Thanks!

**Comment by xhlulu** [comment]
That's very weird, but i'm glad you were able to pinpoint the issue. I am rerunning the CircleCI tests on master, and I'll try to run the tests locally on monday.

Feel free to commit the suggested fix to the tests if you have already written the code to do so. Otherwise, i'll play with the tests monday and i'll try to fix it on my side.

**Comment by xhlulu** [comment]
@mj3cheun is it safe to delete `package-lock.json`? Since we have been using `yarn`* so far, i think it's better to have one lock file (either `yarn.lock` or `package-lock.json`) instead of both.

If you don't have `yarn` installed locally, i can build the lockfile before a release; for now I'm thinking of just removing the `package-lock.json`.

* this is totally my fault, i should've mentioned that at the start of the PR and more clearly in the readme

**Comment by mj3cheun** [comment]
Oh yes no problem at all. I will go ahead and delete `package-lock.json`. I can also add this file to the gitignore. If you don't mind can you build the lockfile? Sorry about that and thanks a lot!

**Comment by xhlulu** [comment]
No worries. the docs in contributing are very confusing when it comes to `yarn` vs `npm`, definitely will need to change those for future contributors!

**Comment by xhlulu** [comment]
@mj3cheun I'm currently looking into the snapshots (seems like they look very weird on percy, but fine locally on py3.7). Once this is resolved, i'm happy to merge this.

Was there anything else you wanted to add this PR?

**Comment by xhlulu** [comment]
And thank you so much for contributing this new feature, as well as taking the time to go through all those tests!

**Comment by mj3cheun** [comment]
Thanks for taking the time to review the PR, I am happy that it is finally getting merged! No there is nothing else that needs to be added to this PR, any further improvements and (hopefully not) bug fixes can be addressed in a second PR.

**Pull request merged**
