### PR TITLE
Upgrade to react-cytoscapejs 2

### PR DESCRIPTION
**Pull request by akx**
## About

I checked that the Webpack builds pass, hoping that CI here would do the rest.

Cc 

## Description of changes 

See above.

## Pre-Merge checklist
- [x] The project was correctly built with `npm run build:all`.
- [x] If there was any conflict, it was solved correctly.
- [ ] All changes were documented in CHANGELOG.md.
- [ ] All tests on CircleCI have passed.
- [ ] All Percy visual changes have been approved.
- [ ] Two people have :dancer:'d the pull request. You can be one of these people if you are a Dash Cytoscape core contributor.

## Reference Issues

See plotly/react-cytoscapejs#99 for the discussion around react-cytoscapejs 2.

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Thanks @akx. Looks like there are some build issues on CI... if you're motivated to dig in you're more than welcome, I've updated the permissions so it should work fine from your fork now, but I'm also happy to let this one wait a bit until someone from Plotly gets a chance to poke around here.

**Comment by akx** [comment]
@alexcjohnson Well, it worked for exactly one build... 😁 

I think #179 is related here; since `pip install` has been set to `--quiet` I can't verify which version of dash is exactly being used, but it's obviously not one with https://github.com/plotly/dash/pull/1995 in, since the one build failed with

```
  File "/home/circleci/project/venv/lib/python3.7/site-packages/dash/dash.py", line 22, in <module>
    from werkzeug.debug.tbtools import get_current_traceback
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/home/circleci/project/venv/lib/python3.7/site-packages/werkzeug/debug/tbtools.py)
```

**Comment by alexcjohnson** [comment]
Yeah weird. Feel free to remove `--quiet` - and thanks for the nudge on #179

**Comment by alexcjohnson** [comment]
Done in #193 - thanks @akx!

**Pull request closed without merging**
