### PR TITLE
implements wheelSensitivity feature #97

### PR DESCRIPTION
**Pull request by kinimesi**
## Pre-Merge checklist
- [x] The project was correctly built with `npm run build:all`.
- [ ] If there was any conflict, it was solved correctly.
- [ ] All changes were documented in CHANGELOG.md.
- [ ] All tests on CircleCI have passed.
- [ ] All Percy visual changes have been approved.
- [ ] Two people have :dancer:'d the pull request. You can be one of these people if you are a Dash Cytoscape core contributor.

## Reference Issues

Closes #[issue number]

## Other comments

### CODE REVIEW

**Review by xhlulu — CHANGES_REQUESTED** [review]
Hey can you add an example inside demos?

And update the docs if this is something relevant to talk about beyond it's obvious use?

Also it'd be nice to have tests for this, but if it's too difficult and you want to wait until after the tests are rewritten, feel free to open and issue and track it

**Comment by kinimesi** [comment]
This feature is exposes `wheelSensitivity` option which is one of the initialization parameters of the Cytoscape.js. This is very similar to the other initialization parameters that dash-cytoscape already has such as `zoom`, `minZoom`, `userZoomingEnabled` and etc. We do not have tests or demos for such features. I don't think that one is necessary for `wheelSensitivity` either. 

It's very obvious to use and one line description was added to the relevant files in the PR (all other similar options also have one line descriptions).

**Comment by alimanfoo** [comment]
Just to mention I'd very much like this feature. Is there any reason why this PR got stalled?

**Comment by ivolake** [comment]
I await this functionality with the greatest anticipation.

**Comment by alexcjohnson** [comment]
Done in #203

**Pull request closed without merging**
