### PR TITLE
Add DashCytoscape.jl v0.3.0

### PR DESCRIPTION
**Pull request by rpkyle**
Closes https://github.com/plotly/dash-cytoscape/issues/136

This PR proposes to contribute v0.3.0 of DashCytoscape for Julia, and to modify the `package.json` to use the same `build:backends` syntax as is currently used in the core Dash component libraries.

For reference, I tested the package build with Julia v1.5.2 and my sample app:

https://gist.github.com/rpkyle/230086c112da16ea3118a7c04e69717a

### CODE REVIEW

**Comment by xhlulu** [comment]
> to use the same build:backends syntax as is currently used in the core Dash component libraries.

Can you update contributing with this information?

**Comment by xhlulu** [comment]
Ok if the title is changed to "Add DashCytoscape.jl **v0.3.0**"

**Comment by rpkyle** [comment]
> > to use the same build:backends syntax as is currently used in the core Dash component libraries.
> 
> Can you update contributing with this information?

fixed in aa4ebbf

**Comment by RohitRathore1** [comment]
@rpkyle is DashCytoscape publicly available for Julia?

**Pull request merged**
